definitions:
  internal_health_controller.HealthResponse:
    properties:
      message:
        example: OK
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      description: Returns the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_health_controller.HealthResponse'
      summary: Get health status
      tags:
      - Health
  /slow:
    get:
      description: Simulates a slow response to test timeout handling
      produces:
      - application/json
      responses:
        "200":
          description: This is a slow response
          schema:
            $ref: '#/definitions/internal_health_controller.HealthResponse'
      summary: Simulate a slow endpoint
      tags:
      - Health
swagger: "2.0"
